### ISSUE TITLE
How do I change the header on slide when using showSlidingBottomSheet()

### ISSUE THREAD

**Issue by mwawrusch** [BendixMa/sliding-sheet#2]
Hi, I looked at the example which shows how to do this when embedding the Slider directly. How do I implement this if I invoke showSlidingBottomSheet()? 
I want to switch from rounded corners to no corners and from a grapper to a close button (fading in and out).

Thanks!

**Comment by BendixMa** [comment]
I released a new version `0.2.0` that changes the way bottom sheets are implemented. It is now possible by calling `rebuild()` on an instance of `SheetController` to rebuild the whole dialog. Important is though that the same `SheetController` is always assigned. See this example:

```dart
Future showBottomSheet(BuildContext context) async {
    final dialogController = SheetController();
    double progress = 0;
    double multiple = 1;

    await showSlidingBottomSheet(
      context,
      builder: (context) {
        return SlidingSheetDialog(
          controller: dialogController,
          snapSpec: const SnapSpec(
            snap: true,
            snappings: const [0.4, 0.7, 1.0],
          ),
          scrollSpec: ScrollSpec.bouncingScroll(),
          color: Colors.white,
          cornerRadius: 16 * multiple,
          listener: (state) {
            progress = state.progress;
            multiple = 1 - interval(0.7, 1.0, progress);
            if (state.extent >= 0.7 || (state.isExpanded && state.scrollOffset < 8.0)) {
              dialogController.rebuild();
            }
          },
          headerBuilder: (context, state) {
            final theme = Theme.of(context);
            final textTheme = theme.textTheme;

            return Material(
              elevation: interval(0.0, 8.0, state.scrollOffset) * 4,
              shadowColor: Colors.black,
              color: Colors.white,
              child: Container(
                padding: EdgeInsets.fromLTRB(
                  16,
                  16 + (MediaQuery.of(context).viewPadding.top * (1 - multiple)),
                  16,
                  16,
                ),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: <Widget>[
                    Text(
                      'Header',
                      style: textTheme.headline,
                    ),
                    Stack(
                      children: <Widget>[
                        IgnorePointer(
                          ignoring: progress > 0.7,
                          child: Opacity(
                            opacity: 1 - interval(0.7, 0.85, progress),
                            child: IconButton(
                              icon: Icon(Icons.keyboard_arrow_up),
                              onPressed: dialogController.expand,
                            ),
                          ),
                        ),
                        IgnorePointer(
                          ignoring: progress < 1.0,
                          child: Opacity(
                            opacity: interval(0.85, 1.0, progress),
                            child: IconButton(
                              icon: Icon(Icons.keyboard_arrow_down),
                              onPressed: () => Navigator.pop(context),
                            ),
                          ),
                        ),
                      ],
                    )
                  ],
                ),
              ),
            );
          },
          builder: (context, state) {
            return Container(
              height: 1200,
              color: Colors.white,
              child: Center(
                child: Text(
                  'This is a bottom sheet dialog!',
                  style: textStyle,
                ),
              ),
            );
          },
        );
      },
    );
  }

// Shrinks animation values inside a specified range. E.g. from .2 - .4 => .3 = 50%.
double interval(double lower, double upper, double progress) {
  assert(lower < upper);

  if (progress > upper) return 1.0;
  if (progress < lower) return 0.0;

  return ((progress - lower) / (upper - lower)).clamp(0.0, 1.0);
}
```

**Comment by mwawrusch** [comment]
Thanks, I will check it out.

**Comment by mwawrusch** [comment]
A few things:
1. A little feature request - please add an optional secondary snap array that handles snapping when closing the sheet. In my case I want to have 0 -> 0.7 -> 1 and then back to 0 when swiping to close.

2. With the new code I get this flex error when swiping to close - the overflow is varying, sometimes 3 pixel, sometimes around 15:

2019-12-01 11:52:29.928655-0800 Runner[30386:5478823] flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
2019-12-01 11:52:29.928755-0800 Runner[30386:5478823] flutter: The following assertion was thrown during layout:
2019-12-01 11:52:29.928789-0800 Runner[30386:5478823] flutter: A RenderFlex overflowed by 9.5 pixels on the bottom.
2019-12-01 11:52:29.928820-0800 Runner[30386:5478823] flutter:
2019-12-01 11:52:29.928856-0800 Runner[30386:5478823] flutter: User-created ancestor of the error-causing widget was:
2019-12-01 11:52:29.928884-0800 Runner[30386:5478823] flutter:   Stack
2019-12-01 11:52:29.928915-0800 Runner[30386:5478823] flutter:   file:///Users/mwawrusch/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/sliding_sheet-0.2.1/lib/src/sheet.dart:535:34
2019-12-01 11:52:29.928940-0800 Runner[30386:5478823] flutter:
2019-12-01 11:52:29.929080-0800 Runner[30386:5478823] flutter: The overflowing RenderFlex has an orientation of Axis.vertical.
2019-12-01 11:52:29.929112-0800 Runner[30386:5478823] flutter: The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
2019-12-01 11:52:29.929139-0800 Runner[30386:5478823] flutter: black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
2019-12-01 11:52:29.929168-0800 Runner[30386:5478823] flutter: Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
2019-12-01 11:52:29.929198-0800 Runner[30386:5478823] flutter: RenderFlex to fit within the available space instead of being sized to their natural size.
2019-12-01 11:52:29.929277-0800 Runner[30386:5478823] flutter: This is considered an error condition because it indicates that there is content that cannot be
2019-12-01 11:52:29.929326-0800 Runner[30386:5478823] flutter: seen. If the content is legitimately bigger than the available space, consider clipping it with a
2019-12-01 11:52:29.929386-0800 Runner[30386:5478823] flutter: ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
2019-12-01 11:52:29.929416-0800 Runner[30386:5478823] flutter: like a ListView.
2019-12-01 11:52:29.929442-0800 Runner[30386:5478823] flutter: The specific RenderFlex in question is: RenderFlex#b6696 relayoutBoundary=up1 OVERFLOWING:
2019-12-01 11:52:29.929477-0800 Runner[30386:5478823] flutter:   needs compositing
2019-12-01 11:52:29.929557-0800 Runner[30386:5478823] flutter:   creator: Column ← Stack ← ClipRRect ← DecoratedBox ← Container ← _SheetContainer ←
2019-12-01 11:52:29.929587-0800 Runner[30386:5478823] flutter:     FractionallySizedBox ← SizedBox.expand ← Stack ← LayoutBuilder ← ConstrainedBox ← Align ← ⋯
2019-12-01 11:52:29.929622-0800 Runner[30386:5478823] flutter:   parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
2019-12-01 11:52:29.929648-0800 Runner[30386:5478823] flutter:   constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=120.5)
2019-12-01 11:52:29.929671-0800 Runner[30386:5478823] flutter:   size: Size(414.0, 120.5)
2019-12-01 11:52:29.929699-0800 Runner[30386:5478823] flutter:   direction: vertical
2019-12-01 11:52:29.929725-0800 Runner[30386:5478823] flutter:   mainAxisAlignment: start
2019-12-01 11:52:29.929751-0800 Runner[30386:5478823] flutter:   mainAxisSize: max
2019-12-01 11:52:29.929780-0800 Runner[30386:5478823] flutter:   crossAxisAlignment: center
2019-12-01 11:52:29.929809-0800 Runner[30386:5478823] flutter:   verticalDirection: down
2019-12-01 11:52:29.929842-0800 Runner[30386:5478823] flutter: ◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤

**Comment by BendixMa** [comment]
I think I was able resolve the overflow issue with version `0.2.2`.

I will think about the additional snap array, though in the current implementation the sheet will choose the used snap based on the velocity of the down or up fling. This is to say that when the sheet is expanded and the user makes a quick down fling (so as the close the sheet) it would to so, while if the user releases the finger with zero velocity it would choose the closest snap to the current position which is I think the preferable solution.

**Comment by BendixMa** [comment]
Version `0.2.4` should solve the overflow error now.

**Comment by mwawrusch** [comment]
Thanks BendixMa, it does, thank you.

**Comment by mwawrusch** [comment]
I do however still have an issue regarding the original question. Using your code sample from above I do the following:

```

Future<void>  showSlider(BuildContext context, String assetId) async {
  final dialogController = SheetController();
  double progress = 0;
  double multiple = 1;

  await showSlidingBottomSheet(
      context,
      builder: (context) {
        return SlidingSheetDialog(
          controller: dialogController,
          snapSpec: const SnapSpec(
            snap: true,
            snappings: const [0.7, 1.0],
          ),
          scrollSpec: ScrollSpec.bouncingScroll(),
          color: Colors.white,
          cornerRadius: 16  * multiple,
          listener: (state) {
            progress = state.progress;
            multiple = 1 - interval(0.7, 1.0, progress);
            if (state.extent >= 0.7 || (state.isExpanded && state.scrollOffset < 8.0)) {
              dialogController.rebuild();
            }
          },
          footerBuilder: (context, state) => DetailFooter(state: state),
          headerBuilder: (context, state) => DetailHeader(state: state),
          builder: (context, state) {
      return Container(
        // height: MediaQuery.of(context).size.height,
        child: Material(color: RojiTheme.colorWhite , child:  DetailContainer(assetId: assetId))

      );
    }, 
    );
  },
);
}



// Shrinks animation values inside a specified range. E.g. from .2 - .4 => .3 = 50%.
double interval(double lower, double upper, double progress) {
  assert(lower < upper);

  if (progress > upper) return 1.0;
  if (progress < lower) return 0.0;

  return ((progress - lower) / (upper - lower)).clamp(0.0, 1.0);
}
```

Now when the ''' // height: MediaQuery.of(context).size.height,''' line is commented out the dialog snaps at 0.3 ish, and the rounding code does not work.

If I add the height... then the content of the dialog is cut off, as it extends beyond the height returned by the media query.

Please help ;)

PS really appreciate your widget and the work you put in.

**Comment by BendixMa** [comment]
If you do not define a snap positioning on the `SnapSpec` it means that the snaps are positioned relative to the total available space which most likely is the same as `MediaQuery.of(context).size.height`.  Now, I would assume that the height of the `DetailContainer` is smaller than 0.7 times the screen height and thus the sheet snaps to the height of your `DetailContainer` and not to `0.7`. This is also why the rounding doesn't work as you rebuild the dialog only when the `extent` is greater than `0.7` which the sheet probably never reaches. It should work if you change it to `state.progress` instead of `state.extent`:
~~~dart
listener: (state) {
    progress = state.progress;
    multiple = 1 - interval(0.7, 1.0, progress);
       if (state.progress >= 0.7 || (state.isExpanded && state.scrollOffset < 8.0)) {
          dialogController.rebuild();
     }
 },
~~~
I think you need to look if your `DetailContainer` is sizing itself correctly as I wasn't able to reproduce the error. Maybe you could try to change the `ListView` to a `Column` with `mainAxisSize` to `MainAxisSize.min` as scrolling is already handled by the sheet.

**Comment by mwawrusch** [comment]
Thanks. The column advice was helpful, and I figure out the reason for the other problem thanks to your help. Basically, we dynamically load the content of the slider, so the height is just the height of a loading indicator when opening the slider but then becomes a 2000 pixels or so.

I solved this by wrapping it like so:

```
final height = MediaQuery.of(context, nullOk: true).size.height ?? 0;
....

 ConstrainedBox(
  constraints: BoxConstraints(
    minHeight: height,
    minWidth: 0.0,
    maxHeight: double.infinity,
    maxWidth: double.infinity,
  ), child:  Material(color: RojiTheme.colorWhite , child:  DetailContainer(assetId: assetId)),
    ));
  },
```

so far it all looks good. Thanks for your help
